package com.boylab.tablescale.base.db.tableDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.boylab.tablescale.base.db.table.Goods;
import com.boylab.tablescale.base.db.table.Record;
import com.boylab.tablescale.base.db.table.User;

import com.boylab.tablescale.base.db.tableDao.GoodsDao;
import com.boylab.tablescale.base.db.tableDao.RecordDao;
import com.boylab.tablescale.base.db.tableDao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsDaoConfig;
    private final DaoConfig recordDaoConfig;
    private final DaoConfig userDaoConfig;

    private final GoodsDao goodsDao;
    private final RecordDao recordDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsDaoConfig = daoConfigMap.get(GoodsDao.class).clone();
        goodsDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        goodsDao = new GoodsDao(goodsDaoConfig, this);
        recordDao = new RecordDao(recordDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Goods.class, goodsDao);
        registerDao(Record.class, recordDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        goodsDaoConfig.clearIdentityScope();
        recordDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public GoodsDao getGoodsDao() {
        return goodsDao;
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
