package com.boylab.tablescale.base.db.tableDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.boylab.tablescale.base.db.table.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property UserName = new Property(1, String.class, "userName", false, "USER_NAME");
        public final static Property UserPass = new Property(2, String.class, "userPass", false, "USER_PASS");
        public final static Property UserPerm = new Property(3, int.class, "userPerm", false, "USER_PERM");
        public final static Property WeighPerm = new Property(4, int.class, "weighPerm", false, "WEIGH_PERM");
        public final static Property ScalePerm = new Property(5, int.class, "scalePerm", false, "SCALE_PERM");
        public final static Property OtherPerm = new Property(6, int.class, "otherPerm", false, "OTHER_PERM");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"USER_NAME\" TEXT," + // 1: userName
                "\"USER_PASS\" TEXT," + // 2: userPass
                "\"USER_PERM\" INTEGER NOT NULL ," + // 3: userPerm
                "\"WEIGH_PERM\" INTEGER NOT NULL ," + // 4: weighPerm
                "\"SCALE_PERM\" INTEGER NOT NULL ," + // 5: scalePerm
                "\"OTHER_PERM\" INTEGER NOT NULL );"); // 6: otherPerm
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(2, userName);
        }
 
        String userPass = entity.getUserPass();
        if (userPass != null) {
            stmt.bindString(3, userPass);
        }
        stmt.bindLong(4, entity.getUserPerm());
        stmt.bindLong(5, entity.getWeighPerm());
        stmt.bindLong(6, entity.getScalePerm());
        stmt.bindLong(7, entity.getOtherPerm());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(2, userName);
        }
 
        String userPass = entity.getUserPass();
        if (userPass != null) {
            stmt.bindString(3, userPass);
        }
        stmt.bindLong(4, entity.getUserPerm());
        stmt.bindLong(5, entity.getWeighPerm());
        stmt.bindLong(6, entity.getScalePerm());
        stmt.bindLong(7, entity.getOtherPerm());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userPass
            cursor.getInt(offset + 3), // userPerm
            cursor.getInt(offset + 4), // weighPerm
            cursor.getInt(offset + 5), // scalePerm
            cursor.getInt(offset + 6) // otherPerm
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setUserName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserPass(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUserPerm(cursor.getInt(offset + 3));
        entity.setWeighPerm(cursor.getInt(offset + 4));
        entity.setScalePerm(cursor.getInt(offset + 5));
        entity.setOtherPerm(cursor.getInt(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
